export const defaultVariables: Record<string, string> = {
  "transition-duration": "150ms",
  "transition-timing-function": "cubic-bezier(0.4, 0, 0.2, 1)",
  "font-family": "var(--font-sans)",
  "mono-font-family": "var(--font-mono)",
} as const;

export const defaultThemeVariables: Record<string, string> = {
  "border-spacing-x": "0",
  "border-spacing-y": "0",
  "translate-x": "initial",
  "translate-y": "initial",
  "scale-x": "initial",
  "scale-y": "initial",
  rotate: "initial",
  "skew-x": "initial",
  "skew-y": "initial",
  "space-y-reverse": "0",
  "space-x-reverse": "0",
  "divide-x-reverse": "0",
  "border-style": "solid",
  "divide-y-reverse": "0",
  "gradient-position": "initial",
  "gradient-from": "#0000",
  "gradient-via": "#0000",
  "gradient-to": "#0000",
  "gradient-stops": "initial",
  "gradient-via-stops": "initial",
  "gradient-from-position": "0%",
  "gradient-via-position": "50%",
  "gradient-to-position": "100%",
  leading: "initial",
  "font-weight": "initial",
  tracking: "initial",
  ordinal: "initial",
  "slashed-zero": "initial",
  "numeric-figure": "initial",
  "numeric-spacing": "initial",
  "numeric-fraction": "initial",
  shadow: "0 0 #0000",
  "shadow-color": "initial",
  "shadow-alpha": "100%",
  "inset-shadow": "0 0 #0000",
  "inset-shadow-color": "initial",
  "inset-shadow-alpha": "100%",
  "ring-color": "initial",
  "ring-shadow": "0 0 #0000",
  "inset-ring-color": "initial",
  "inset-ring-shadow": "0 0 #0000",
  "ring-inset": "initial",
  "ring-offset-width": "0px",
  "ring-offset-color": "#fff",
  "ring-offset-shadow": "0 0 #0000",
  "outline-style": "solid",
  blur: "initial",
  brightness: "initial",
  contrast: "initial",
  grayscale: "initial",
  "hue-rotate": "initial",
  invert: "initial",
  opacity: "initial",
  saturate: "initial",
  sepia: "initial",
  "drop-shadow": "initial",
  "drop-shadow-color": "initial",
  "drop-shadow-alpha": "100%",
  "drop-shadow-size": "initial",
  duration: "initial",
  ease: "initial",
  "text-shadow-color": "initial",
  "text-shadow-alpha": "100%",
} as const;
